### GET ALL
GET {{protocol}}://{{host}}/api/{{version}}/inventory
Content-Type: application/json

### GET STOCK
GET {{protocol}}://{{host}}/api/{{version}}/inventory/stock
Content-Type: application/json

### ADD OR UPDATE
POST  {{protocol}}://{{host}}/api/{{version}}/inventory
Content-Type: application/json

{
    "id_producto": null,
    "producto": "Guantes"
}