### LOGIN
POST {{protocol}}://{{host}}/api/{{version}}/user/sing-in 
Content-Type: application/json

{
    "usuario": "m.ortega",
    "contrasenia": "Abc123**"
}

### GET ALL
GET {{protocol}}://{{host}}/api/{{version}}/user
Content-Type: application/json


### ADD OR UPDATE
PUT {{protocol}}://{{host}}/api/{{version}}/user
Content-Type: application/json

{
    "id_usuario": 2,
    "nombre": "Invitado Pruebas",
    "correo": "pruebas@gmail.com",
    "usuario": "invitado",
    "estado": "1"
}