-- MySQL Script generated by MySQL Workbench
-- Fri Feb  2 15:36:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_combat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_combat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_combat` DEFAULT CHARACTER SET utf8 ;
USE `bd_combat` ;

-- -----------------------------------------------------
-- Table `bd_combat`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_combat`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(100) NOT NULL,
  `imagen` VARCHAR(200) NULL,
  `estado` CHAR(1) NULL DEFAULT 1,
  `fecha_creacion` DATETIME NULL DEFAULT current_timestamp(),
  `fecha_edicion` DATETIME NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_combat`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_combat`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(100) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NULL DEFAULT current_timestamp(),
  `fecha_edicion` TIMESTAMP NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_combat`.`medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_combat`.`medida` (
  `id_medida` INT NOT NULL AUTO_INCREMENT,
  `medida` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NULL DEFAULT current_timestamp(),
  `fecha_edicion` TIMESTAMP NULL,
  PRIMARY KEY (`id_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_combat`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_combat`.`color` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NULL DEFAULT current_timestamp(),
  `fecha_edicion` TIMESTAMP NULL,
  PRIMARY KEY (`id_color`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_combat`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_combat`.`inventario` (
  `id_inventario` BIGINT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_medida` INT NOT NULL,
  `id_color` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `disponible` INT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `precio_compra` DECIMAL(10,2) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NULL DEFAULT current_timestamp(),
  `fecha_edicion` TIMESTAMP NULL,
  PRIMARY KEY (`id_inventario`),
  INDEX `fk_inventario_producto_idx` (`id_producto` ASC),
  INDEX `fk_inventario_medida1_idx` (`id_medida` ASC),
  INDEX `fk_inventario_color1_idx` (`id_color` ASC),
  INDEX `fk_inventario_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_inventario_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bd_combat`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_medida1`
    FOREIGN KEY (`id_medida`)
    REFERENCES `bd_combat`.`medida` (`id_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_color1`
    FOREIGN KEY (`id_color`)
    REFERENCES `bd_combat`.`color` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_combat`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_combat`.`puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_combat`.`puesto` (
  `id_puesto` INT NOT NULL AUTO_INCREMENT,
  `puesto` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NULL DEFAULT current_timestamp(),
  `fecha_edicion` TIMESTAMP NULL,
  PRIMARY KEY (`id_puesto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_combat`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_combat`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_puesto` INT NOT NULL,
  `id_usuario` INT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `imagen` VARCHAR(200) NULL,
  `celular` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `dpi` VARCHAR(45) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT current_timestamp(),
  `fecha_edicion` TIMESTAMP NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_empleado_puesto1_idx` (`id_puesto` ASC),
  INDEX `fk_empleado_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_empleado_puesto1`
    FOREIGN KEY (`id_puesto`)
    REFERENCES `bd_combat`.`puesto` (`id_puesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_combat`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_combat`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_combat`.`orden` (
  `id_orden` INT NOT NULL AUTO_INCREMENT,
  `id_vendedor` INT NOT NULL,
  `no_factura` VARCHAR(45) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `direccion` TEXT NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha` DATE NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT current_timestamp(),
  `fecha_edicion` TIMESTAMP NULL,
  PRIMARY KEY (`id_orden`),
  INDEX `fk_orden_empleado1_idx` (`id_vendedor` ASC),
  CONSTRAINT `fk_orden_empleado1`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `bd_combat`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_combat`.`detalle_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_combat`.`detalle_orden` (
  `id_orden` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `producto` VARCHAR(100) NOT NULL,
  `detalle` TEXT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `medida` VARCHAR(45) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NULL DEFAULT current_timestamp(),
  `fecha_edicion` TIMESTAMP NULL,
  INDEX `fk_detalle_orden_orden1_idx` (`id_orden` ASC),
  INDEX `fk_detalle_orden_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_detalle_orden_orden1`
    FOREIGN KEY (`id_orden`)
    REFERENCES `bd_combat`.`orden` (`id_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_orden_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bd_combat`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
